resolver: lts-10.2
packages:
- location: .

extra-deps:
- extra-1.5.3
- monad-journal-0.7.2
- optparse-applicative-0.13.2.0
- either-4.4.1.1
- cabal-helper-0.8.0.2
- core

flags: {}
extra-package-dbs: []
